### ISSUE TITLE
re-use the same config, with different seed

### ISSUE THREAD

**Issue by esheldon** [esheldon/psfsim_config#6]
The current configs will evolve into representing an exposure, with N CCD images.  We want to be able to re-use the same config again just changing the seed.  Is this straightforward to do on the command line?

**Comment by rmjarvis** [comment]
https://github.com/GalSim-developers/GalSim/wiki/Config-Documentation-v1.4#the-galsim-executable

**Comment by esheldon** [comment]
example

```
galsim config.yaml  image.random_seed=43342
```
